components:
  schemas:
    GetSellerItemsRs:
      type: array
      items:
        type: object
        properties:
          seller_id:
            type: string
            example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
          name:
            type: string
            example: Test Item
          description:
            type: string
            example: This is a sample seller item description.
          price:
            type: number
            format: double
            example: 0.01
          stock_level:
            $ref: '/api/docs/enum/StockLevelType.yml#/components/schemas/StockLevelType'
          image:
            type: string
            format: binary
            example: https://example.com/image.jpg
          duration:
            type: number
            example: 1
          created_at:
            type: string
            format: date-time
            example: 2024-12-21T00:00:00.000Z
          updated_at:
            type: string
            format: date-time
            example: 2024-12-21T00:00:00.000Z
          expired_by:
            type: string
            format: date-time
            example: 2024-12-28T00:00:00.000Z
          _id:
            type: string
            example: 66741c62b175e7d059a2639e
          __v:
            type: number
            example: 0
    
    GetSellerItemRs:
      type: object
      properties:
        seller_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        name:
          type: string
          example: Test Item
        description:
          type: string
          example: This is a sample seller item description.
        price:
          type: number
          format: double
          example: 0.01
        stock_level:
          $ref: '/api/docs/enum/StockLevelType.yml#/components/schemas/StockLevelType'
        image:
          type: string
          format: binary
          example: https://example.com/image.jpg
        duration:
          type: number
          example: 1
        created_at:
          type: string
          format: date-time
          example: 2024-12-21T00:00:00.000Z
        updated_at:
          type: string
          format: date-time
          example: 2024-12-21T00:00:00.000Z
        expired_by:
          type: string
          format: date-time
          example: 2024-12-28T00:00:00.000Z
        _id:
          type: string
          example: 66741c62b175e7d059a2639e
        __v:
          type: number
          example: 0

    AddSellerItemRq:
      type: object
      properties:
        _id:
          type: string
          example: 66741c62b175e7d059a2639e
        seller_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        name:
          type: string
          example: Test Item
        description:
          type: string
          example: This is a sample seller item description.
        price:
          type: number
          format: double
          example: 0.01
        stock_level:
          $ref: '/api/docs/enum/StockLevelType.yml#/components/schemas/StockLevelType'
        image:
          type: string
          format: binary
          example: https://example.com/image.jpg
        duration:
          type: number
          example: 1

    AddSellerItemRs:
      type: object
      properties:
        seller_id:
          type: string
          example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
        name:
          type: string
          example: Test Item
        description:
          type: string
          example: This is a sample seller item description.
        price:
          type: number
          format: double
          example: 0.01
        stock_level:
          $ref: '/api/docs/enum/StockLevelType.yml#/components/schemas/StockLevelType'
        image:
          type: string
          format: binary
          example: https://example.com/image.jpg
        duration:
          type: number
          example: 1
        created_at:
          type: string
          format: date-time
          example: 2024-12-21T00:00:00.000Z
        updated_at:
          type: string
          format: date-time
          example: 2024-12-21T00:00:00.000Z
        expired_by:
          type: string
          format: date-time
          example: 2024-12-28T00:00:00.000Z
        _id:
          type: string
          example: 66741c62b175e7d059a2639e
        __v:
          type: number
          example: 0

    DeleteSellerItemRs:
      type: object
      properties:
        message:
          type: string
          example: Seller item deleted successfully.
        deletedSellerItem:
          type: object
          properties:  
            seller_id:
              type: string
              example: 0d367ba3-a2e8-4380-86c3-ab7c0b7890c0
            name:
              type: string
              example: Test Item
            description:
              type: string
              example: This is a sample seller item description.
            price:
              type: number
              format: double
              example: 0.01
            stock_level:
              $ref: '/api/docs/enum/StockLevelType.yml#/components/schemas/StockLevelType'
            image:
              type: string
              format: binary
              example: https://example.com/image.jpg
            duration:
              type: number
              example: 1
            created_at:
              type: string
              format: date-time
              example: 2024-12-21T00:00:00.000Z
            updated_at:
              type: string
              format: date-time
              example: 2024-12-21T00:00:00.000Z
            expired_by:
              type: string
              format: date-time
              example: 2024-12-28T00:00:00.000Z
            _id:
              type: string
              example: 66741c62b175e7d059a2639e
            __v:
              type: number
              example: 0